# Generated by Django 5.1.15 on 2026-02-13 08:11

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=30, verbose_name='from status')),
                ('to_status', models.CharField(max_length=30, verbose_name='to status')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'order status log',
                'verbose_name_plural': 'order status logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('client_type', models.CharField(choices=[('pharmacy', 'Pharmacy'), ('institution', 'Institution'), ('individual', 'Individual')], default='individual', max_length=20, verbose_name='client type')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('nif', models.CharField(help_text='Tax identification number', max_length=20, unique=True, verbose_name='NIF')),
                ('infarmed_code', models.CharField(blank=True, max_length=50, verbose_name='Infarmed code')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='order number')),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('in_person', 'In Person'), ('phone', 'Phone')], default='in_person', max_length=20, verbose_name='source')),
                ('status', django_fsm.FSMField(choices=[('new_request', 'New Request'), ('waiting_for_quote', 'Waiting for Quote'), ('waiting_for_recipe', 'Waiting for Recipe'), ('ready_for_production', 'Ready for Production'), ('in_production', 'In Production'), ('ready', 'Ready'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('error', 'Error')], db_index=True, default='new_request', max_length=50, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='priority')),
                ('prescription_file', models.FileField(blank=True, upload_to='prescriptions/', verbose_name='prescription file')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='quantity')),
                ('unit', models.CharField(default='un', max_length=20, verbose_name='unit')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='unit price')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
    ]
