# Generated by Django 5.1.15 on 2026-02-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pharmacy_auditlog_pharmacy_consent_pharmacy_and_more'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.pharmacy', verbose_name='pharmacy'),
        ),
        migrations.AddField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.pharmacy', verbose_name='pharmacy'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nif',
            field=models.CharField(help_text='Tax identification number', max_length=20, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, verbose_name='order number'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('pharmacy', 'nif')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('pharmacy', 'order_number')},
        ),
    ]
