# Generated by Django 5.1.15 on 2026-02-13 08:11

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('pharmaceutical_form', models.CharField(help_text='e.g., cream, capsule, solution', max_length=100, verbose_name='pharmaceutical form')),
                ('is_multi_stage', models.BooleanField(default=False, verbose_name='multi-stage')),
                ('shelf_life_days', models.PositiveIntegerField(default=90, verbose_name='shelf life (days)')),
                ('storage_conditions', models.CharField(blank=True, max_length=255, verbose_name='storage conditions')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'formulation',
                'verbose_name_plural': 'formulations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FormulationIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='quantity')),
                ('unit', models.CharField(default='g', max_length=20, verbose_name='unit')),
                ('is_active_ingredient', models.BooleanField(default=False, verbose_name='active ingredient')),
                ('order_of_addition', models.PositiveIntegerField(default=0, verbose_name='order of addition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='production.formulation', verbose_name='formulation')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulation_ingredients', to='inventory.rawmaterial', verbose_name='raw material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'formulation ingredient',
                'verbose_name_plural': 'formulation ingredients',
                'ordering': ['order_of_addition'],
            },
        ),
        migrations.CreateModel(
            name='FormulationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('step_number', models.PositiveIntegerField(verbose_name='step number')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='estimated duration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.formulation', verbose_name='formulation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'formulation step',
                'verbose_name_plural': 'formulation steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('doctor_name', models.CharField(max_length=255, verbose_name='doctor name')),
                ('doctor_license', models.CharField(blank=True, max_length=50, verbose_name='doctor license')),
                ('patient_name', models.CharField(max_length=255, verbose_name='patient name')),
                ('patient_tax_number', models.CharField(blank=True, max_length=20, verbose_name='patient NIF')),
                ('file', models.FileField(blank=True, upload_to='prescriptions/rx/', verbose_name='prescription file')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='orders.order', verbose_name='order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='validated by')),
            ],
            options={
                'verbose_name': 'prescription',
                'verbose_name_plural': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('batch_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='batch number')),
                ('status', django_fsm.FSMField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('quality_check', 'Quality Check'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('complete', 'Complete')], db_index=True, default='planned', max_length=50, verbose_name='status')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('production_parameters', models.JSONField(blank=True, default=dict, verbose_name='production parameters')),
                ('quantity_produced', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='quantity produced')),
                ('unit', models.CharField(default='un', max_length=20, verbose_name='unit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='production.formulation', verbose_name='formulation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='orders.order', verbose_name='order')),
                ('produced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_batches', to=settings.AUTH_USER_MODEL, verbose_name='produced by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_batches', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
            ],
            options={
                'verbose_name': 'production batch',
                'verbose_name_plural': 'production batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchMaterialUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('quantity_used', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='quantity used')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_usage', to='inventory.lot', verbose_name='lot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usage', to='production.productionbatch', verbose_name='batch')),
            ],
            options={
                'verbose_name': 'batch material usage',
                'verbose_name_plural': 'batch material usage',
            },
        ),
        migrations.CreateModel(
            name='ProductionStepLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='parameters')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='production.productionbatch', verbose_name='batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_steps', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_logs', to='production.formulationstep', verbose_name='step')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'production step log',
                'verbose_name_plural': 'production step logs',
                'ordering': ['step__step_number'],
            },
        ),
    ]
