# Generated by Django 5.1.15 on 2026-02-13 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='dosage_instructions',
            field=models.TextField(blank=True, verbose_name='dosage instructions'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='route_of_administration',
            field=models.CharField(blank=True, help_text='e.g., oral, topical, nasal', max_length=100, verbose_name='route of administration'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_address',
            field=models.TextField(blank=True, verbose_name='patient address'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='label_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='label generated at'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='special_precautions',
            field=models.TextField(blank=True, verbose_name='special precautions'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='storage_conditions',
            field=models.CharField(blank=True, help_text='Batch-level override; falls back to formulation', max_length=255, verbose_name='storage conditions'),
        ),
        migrations.CreateModel(
            name='BatchCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('raw_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='raw material cost')),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='packaging cost')),
                ('preparation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preparation fee')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total cost')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='production.productionbatch', verbose_name='batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'batch cost',
                'verbose_name_plural': 'batch costs',
            },
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('appearance', models.CharField(max_length=255, verbose_name='appearance')),
                ('odor', models.CharField(blank=True, max_length=255, verbose_name='odor')),
                ('texture', models.CharField(blank=True, max_length=255, verbose_name='texture')),
                ('ph_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='pH value')),
                ('expected_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='expected weight/volume')),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='actual weight/volume')),
                ('weight_deviation_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='weight deviation (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='passed')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='performed at')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_control', to='production.productionbatch', verbose_name='batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_performed', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'quality control',
                'verbose_name_plural': 'quality controls',
            },
        ),
    ]
