# Generated by Django 5.1.15 on 2026-02-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pharmacy_auditlog_pharmacy_consent_pharmacy_and_more'),
        ('production', '0002_formulation_dosage_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulations', to='core.pharmacy', verbose_name='pharmacy'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.pharmacy', verbose_name='pharmacy'),
        ),
        migrations.AlterField(
            model_name='formulation',
            name='code',
            field=models.CharField(max_length=50, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='batch_number',
            field=models.CharField(editable=False, max_length=30, verbose_name='batch number'),
        ),
        migrations.AlterUniqueTogether(
            name='formulation',
            unique_together={('pharmacy', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='productionbatch',
            unique_together={('pharmacy', 'batch_number')},
        ),
    ]
