# Generated by Django 5.1.15 on 2026-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_formulation_pharmacy_productionbatch_pharmacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulation',
            name='base_quantity',
            field=models.DecimalField(decimal_places=3, default=100, help_text='Base quantity the ingredient amounts refer to (e.g., 100 for 100g)', max_digits=10, verbose_name='base quantity'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='base_unit',
            field=models.CharField(default='g', help_text='Unit of the base quantity (e.g., g, mL)', max_length=20, verbose_name='base unit'),
        ),
    ]
