# Generated by Django 5.1.15 on 2026-02-21 18:49

import apps.core.fields
import apps.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pharmacy_dpo_email_pharmacy_dpo_name_and_more'),
        ('production', '0004_formulation_base_quantity_formulation_base_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='file',
            field=models.FileField(blank=True, upload_to='prescriptions/rx/', validators=[apps.core.validators.FileValidator()], verbose_name='prescription file'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_address',
            field=apps.core.fields.EncryptedTextField(blank=True, verbose_name='patient address'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_name',
            field=apps.core.fields.EncryptedCharField(max_length=500, verbose_name='patient name'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_tax_number',
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='patient NIF'),
        ),
        migrations.CreateModel(
            name='EquipmentCalibration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('equipment_name', models.CharField(max_length=255, verbose_name='equipment name')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='serial number')),
                ('calibration_date', models.DateField(verbose_name='calibration date')),
                ('next_calibration_date', models.DateField(verbose_name='next calibration date')),
                ('certificate_file', models.FileField(blank=True, upload_to='calibrations/', validators=[apps.core.validators.FileValidator()], verbose_name='certificate file')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations_performed', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='core.pharmacy', verbose_name='pharmacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'equipment calibration',
                'verbose_name_plural': 'equipment calibrations',
                'ordering': ['-calibration_date'],
            },
        ),
    ]
