# Generated by Django 5.1.15 on 2026-02-13 07:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('street_extra', models.CharField(blank=True, max_length=255, verbose_name='street (line 2)')),
                ('postal_code', models.CharField(max_length=10, verbose_name='postal code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='district')),
                ('country', models.CharField(default='PT', max_length=2, verbose_name='country')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('anonymize', 'Anonymize')], max_length=20, verbose_name='action')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='model')),
                ('object_id', models.CharField(blank=True, max_length=255, verbose_name='object ID')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('purpose', models.CharField(choices=[('data_processing', 'Data Processing'), ('marketing', 'Marketing'), ('third_party', 'Third Party Sharing'), ('research', 'Research')], max_length=30, verbose_name='purpose')),
                ('legal_basis', models.CharField(choices=[('consent', 'Consent'), ('contract', 'Contract Performance'), ('legal_obligation', 'Legal Obligation'), ('legitimate_interest', 'Legitimate Interest')], max_length=30, verbose_name='legal basis')),
                ('granted_at', models.DateTimeField(blank=True, null=True, verbose_name='granted at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consent',
                'verbose_name_plural': 'consents',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('front_desk', 'Front Desk'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='role')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('professional_license', models.CharField(blank=True, help_text='Infarmed professional license number', max_length=50, verbose_name='professional license')),
                ('preferred_language', models.CharField(choices=[('pt-pt', 'Português'), ('en', 'English')], default='pt-pt', max_length=5, verbose_name='preferred language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
