# Generated by Django 5.1.15 on 2026-02-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='license expiry date'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_verified',
            field=models.BooleanField(default=False, verbose_name='license verified'),
        ),
    ]
