# Generated by Django 5.1.15 on 2026-02-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='dpo_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='DPO email'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='dpo_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='DPO name'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='dpo_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='DPO phone'),
        ),
    ]
