# Generated by Django 5.1.15 on 2026-02-13 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('nif', models.CharField(max_length=20, unique=True, verbose_name='NIF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('cas_number', models.CharField(blank=True, help_text='Chemical Abstracts Service', max_length=30, verbose_name='CAS number')),
                ('default_unit', models.CharField(default='g', max_length=20, verbose_name='default unit')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='minimum stock')),
                ('reorder_point', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='reorder point')),
                ('is_controlled_substance', models.BooleanField(default=False, verbose_name='controlled substance')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'raw material',
                'verbose_name_plural': 'raw materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('lot_number', models.CharField(max_length=50, verbose_name='lot number')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='initial quantity')),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='current quantity')),
                ('received_date', models.DateField(verbose_name='received date')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('certificate_of_analysis', models.FileField(blank=True, upload_to='inventory/coa/', verbose_name='certificate of analysis')),
                ('is_quarantined', models.BooleanField(default=False, verbose_name='quarantined')),
                ('is_exhausted', models.BooleanField(default=False, verbose_name='exhausted')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.rawmaterial', verbose_name='raw material')),
            ],
            options={
                'verbose_name': 'lot',
                'verbose_name_plural': 'lots',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('production_use', 'Production Use'), ('adjustment', 'Adjustment'), ('disposal', 'Disposal'), ('return', 'Return')], max_length=20, verbose_name='type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='quantity')),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='balance after')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.lot', verbose_name='lot')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
