# Generated by Django 5.1.15 on 2026-02-13 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cost per base unit (e.g., per gram, per mL)', max_digits=10, null=True, verbose_name='cost per unit'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='pharmacopeia_reference',
            field=models.CharField(blank=True, help_text='e.g., FP X, Ph.Eur., USP', max_length=100, verbose_name='pharmacopeia reference'),
        ),
        migrations.CreateModel(
            name='ProhibitedSubstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('cas_number', models.CharField(blank=True, max_length=30, verbose_name='CAS number')),
                ('regulation', models.CharField(default='Deliberação 1985/2015', max_length=100, verbose_name='regulation')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'prohibited substance',
                'verbose_name_plural': 'prohibited substances',
                'ordering': ['name'],
            },
        ),
    ]
