# Generated by Django 5.1.15 on 2026-02-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pharmacy_auditlog_pharmacy_consent_pharmacy_and_more'),
        ('inventory', '0003_lot_cost_per_unit_rawmaterial_pharmacopeia_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.pharmacy', verbose_name='pharmacy'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.pharmacy', verbose_name='pharmacy'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='code',
            field=models.CharField(max_length=50, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nif',
            field=models.CharField(max_length=20, verbose_name='NIF'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterial',
            unique_together={('pharmacy', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('pharmacy', 'nif')},
        ),
    ]
