# Generated by Django 5.1.15 on 2026-02-21 18:49

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rawmaterial_pharmacy_supplier_pharmacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='certificate_of_analysis',
            field=models.FileField(blank=True, upload_to='inventory/coa/', validators=[apps.core.validators.FileValidator()], verbose_name='certificate of analysis'),
        ),
    ]
