# Generated by Django 5.1.15 on 2026-02-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pharmacy_auditlog_pharmacy_consent_pharmacy_and_more'),
        ('invoicing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.pharmacy', verbose_name='pharmacy'),
        ),
        migrations.AddField(
            model_name='quote',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.pharmacy', verbose_name='pharmacy'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=30, verbose_name='invoice number'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(editable=False, max_length=20, verbose_name='quote number'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('pharmacy', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('pharmacy', 'quote_number')},
        ),
    ]
